### ISSUE TITLE
GitHub page Organisation

### ISSUE THREAD

**Issue by jvoigtlaender** [chemmi/elm-rocket#1]
Der `gh-pages` Branch könnte bis auf das Kompilat (`.html` Datei) eigentlich leer gehalten werden. In der `README.md` des `master` Branches wäre Angabe des Links `https://username.github.io/projectname/filename.html` sinnvoll.

**Comment by chemmi** [comment]
Hab ich beides soweit möglich berücksichtigt. Vielen Dank fürs Vorbeischauen!
