### ISSUE TITLE
etwas "Code-Kritik"

### ISSUE THREAD

**Issue by jvoigtlaender** [chemmi/elm-rocket#2]
Dinge, die mir beim Durchschauen aufgefallen sind:

Ich würde mehr mit Record-Patternmatching arbeiten. Also zum Beispiel dies:

``` elm
isWin : PlayData -> Bool
isWin data =
    let
        world =
            data.world
...
```

ersetzen durch:

``` elm
isWin : PlayData -> Bool
isWin { world } =
    let
...
```

Falls auch `data` als Ganzes noch gebraucht würde, ginge das per:

``` elm
isWin ({ world } as data) =
...
```

Folgendes ist etwas subtil, aber auf Grund der Weise wie Sie `keyBinding` verwenden, wäre es insgesamt effizienter statt so:

``` elm
keyBinding : Model -> KeyCode -> Key
keyBinding model code =
    case model of
        Play _ ->
            case fromCode code of
...
```

so zu definieren:

``` elm
keyBinding : Model -> KeyCode -> Key
keyBinding model =
    case model of
        Play _ ->
            \code -> case fromCode code of
...
```

Wären wir in Haskell und hätten `hlint` zur Verfügung, würden Sie an verschiedenen Stellen (zum Beispiel in der `subscriptions`-Funktion) auf überflüssige Klammern hingewiesen.

`(\_ -> TimerTick)` -> `always TimerTick`?

In einer Situation wie:

``` elm
            -- others should not happen when calling updateLanding
            _ ->
                data
```

würde ich empfehlen, einen `Debug.crash`-Aufruf hinzuschreiben. Das ist klarer als ein Kommentar, und vor allem kriegen Sie beim Testen noch mit, ob Ihre Annahme ("should") nicht doch verletzt wird.

`NoMsg` wird nicht benötigt, oder?

Die Funktion `markPlatform` sieht aus als würde sie vielleicht durch irgendeinen Helfer aus http://package.elm-lang.org/packages/elm-community/list-extra erschlagen, und falls nicht könnte sie vielleicht einen neuen Helfer in diesem Paket motivieren.

`(\ps -> all (\p -> p.marked) ps)` -> `all (\p -> p.marked)` -> `all .marked`

**Comment by chemmi** [comment]
Vielen Dank für das Feedback! In list-extra habe ich genau das richtige gefunden
